### ISSUE TITLE
npTDMS old scripts not working with version 1.3.0

### ISSUE THREAD

**Issue by rddaz2013** [adamreeve/npTDMS#241] opened 2021-05-20 12:34 UTC
Hello

I am using npTDMS with Google Colab and have some trouble with the new version 1.3.0

**Version 0.24 fine
Version 1.2 fine
Version 1.3 no Scaling and not loading dataset complete**

I will soon provide data and code to reproduce the bug

René

----------------
Otherwise, a big thank you for taking care of this project, it has saved me a lot of work.

**Comment by adamreeve** [comment] 2021-05-21 19:11
Hi, thanks for the bug report. If you can provide an example data file that reproduces this problem that would be great.

**Comment by adamreeve** [comment] 2022-06-15 22:23
I'm closing this due to lack of information, please reopen if you can provide a way to reproduce the issue.

**Closed by adamreeve** 2022-06-15 22:23 UTC
Labels: Bug
